
version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17  
  pre_build:
    commands:
      - echo "Installing Maven dependencies..."
      - mvn clean install -DskipTests=true   
  build:
    commands:
      - echo "Building Spring MVC application..."
      - mvn package   
  post_build:
    commands:
      - echo "Build completed successfully!"
artifacts:
  files:
    - target/*.war   
    - scripts/*.sh
    - appspec.yml
  discard-paths: yes   
